[build]
  publish = "."
  ignore = "exit 1"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/requests"
  to = "/request.html"
  status = 200

[[redirects]]
  from = "/demandesspeciales"
  to = "/demandespeciale.html"
  status = 200

[[redirects]]
  from = "/demandespeciale"
  to = "/demandespeciale.html"
  status = 200
